//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeForm.MedDocService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/", ConfigurationName="MedDocService.DocServiceSoap")]
    public interface DocServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.healthcare.supcon.com/wsmeddoc/GetDocInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbTypeBase))]
        short GetDocInfos(string szPatientID, string szVisitID, string szVisitType, System.DateTime dtVisitTime, string szDocTypeID, ref PracticeForm.MedDocService.MedDocInfo[] lstDocInfos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.healthcare.supcon.com/wsmeddoc/ConvertToHTML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbTypeBase))]
        string ConvertToHTML(string szPatientID, string szVisitID, string[] arrDocIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.healthcare.supcon.com/wsmeddoc/GetDocsHTML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbTypeBase))]
        string GetDocsHTML(string[] arrDocIDs);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class MedDocInfo : DbTypeBase {
        
        private string[] docContentField;
        
        private string docIDField;
        
        private string docTypeIDField;
        
        private string docTitleField;
        
        private System.DateTime docTimeField;
        
        private string docSetIDField;
        
        private int docVersionField;
        
        private string creatorIDField;
        
        private string creatorNameField;
        
        private string modifierIDField;
        
        private string modifierNameField;
        
        private System.DateTime modifyTimeField;
        
        private string patientIDField;
        
        private string patientNameField;
        
        private string visitIDField;
        
        private System.DateTime visitTimeField;
        
        private string visitTypeField;
        
        private string deptCodeField;
        
        private string deptNameField;
        
        private string signCodeField;
        
        private string confidCodeField;
        
        private int orderValueField;
        
        private bool needCombinField;
        
        private string fileTypeField;
        
        private string fileNameField;
        
        private string filePathField;
        
        private System.DateTime recordTimeField;
        
        private string statusDescField;
        
        private System.DateTime requestSignDateField;
        
        private System.DateTime parentSignDateField;
        
        private System.DateTime superSignDateField;
        
        private string templetIDField;
        
        private string printAuditorGradeField;
        
        private string printAuditorIDField;
        
        private string printAuditorNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] DocContent {
            get {
                return this.docContentField;
            }
            set {
                this.docContentField = value;
                this.RaisePropertyChanged("DocContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
                this.RaisePropertyChanged("DocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocTypeID {
            get {
                return this.docTypeIDField;
            }
            set {
                this.docTypeIDField = value;
                this.RaisePropertyChanged("DocTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocTitle {
            get {
                return this.docTitleField;
            }
            set {
                this.docTitleField = value;
                this.RaisePropertyChanged("DocTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DocTime {
            get {
                return this.docTimeField;
            }
            set {
                this.docTimeField = value;
                this.RaisePropertyChanged("DocTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocSetID {
            get {
                return this.docSetIDField;
            }
            set {
                this.docSetIDField = value;
                this.RaisePropertyChanged("DocSetID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DocVersion {
            get {
                return this.docVersionField;
            }
            set {
                this.docVersionField = value;
                this.RaisePropertyChanged("DocVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CreatorID {
            get {
                return this.creatorIDField;
            }
            set {
                this.creatorIDField = value;
                this.RaisePropertyChanged("CreatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreatorName {
            get {
                return this.creatorNameField;
            }
            set {
                this.creatorNameField = value;
                this.RaisePropertyChanged("CreatorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ModifierID {
            get {
                return this.modifierIDField;
            }
            set {
                this.modifierIDField = value;
                this.RaisePropertyChanged("ModifierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ModifierName {
            get {
                return this.modifierNameField;
            }
            set {
                this.modifierNameField = value;
                this.RaisePropertyChanged("ModifierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime ModifyTime {
            get {
                return this.modifyTimeField;
            }
            set {
                this.modifyTimeField = value;
                this.RaisePropertyChanged("ModifyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PatientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
                this.RaisePropertyChanged("PatientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PatientName {
            get {
                return this.patientNameField;
            }
            set {
                this.patientNameField = value;
                this.RaisePropertyChanged("PatientName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string VisitID {
            get {
                return this.visitIDField;
            }
            set {
                this.visitIDField = value;
                this.RaisePropertyChanged("VisitID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime VisitTime {
            get {
                return this.visitTimeField;
            }
            set {
                this.visitTimeField = value;
                this.RaisePropertyChanged("VisitTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string VisitType {
            get {
                return this.visitTypeField;
            }
            set {
                this.visitTypeField = value;
                this.RaisePropertyChanged("VisitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("DeptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DeptName {
            get {
                return this.deptNameField;
            }
            set {
                this.deptNameField = value;
                this.RaisePropertyChanged("DeptName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SignCode {
            get {
                return this.signCodeField;
            }
            set {
                this.signCodeField = value;
                this.RaisePropertyChanged("SignCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ConfidCode {
            get {
                return this.confidCodeField;
            }
            set {
                this.confidCodeField = value;
                this.RaisePropertyChanged("ConfidCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int OrderValue {
            get {
                return this.orderValueField;
            }
            set {
                this.orderValueField = value;
                this.RaisePropertyChanged("OrderValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool NeedCombin {
            get {
                return this.needCombinField;
            }
            set {
                this.needCombinField = value;
                this.RaisePropertyChanged("NeedCombin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
                this.RaisePropertyChanged("FilePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public System.DateTime RecordTime {
            get {
                return this.recordTimeField;
            }
            set {
                this.recordTimeField = value;
                this.RaisePropertyChanged("RecordTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
                this.RaisePropertyChanged("StatusDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public System.DateTime RequestSignDate {
            get {
                return this.requestSignDateField;
            }
            set {
                this.requestSignDateField = value;
                this.RaisePropertyChanged("RequestSignDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public System.DateTime ParentSignDate {
            get {
                return this.parentSignDateField;
            }
            set {
                this.parentSignDateField = value;
                this.RaisePropertyChanged("ParentSignDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public System.DateTime SuperSignDate {
            get {
                return this.superSignDateField;
            }
            set {
                this.superSignDateField = value;
                this.RaisePropertyChanged("SuperSignDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string TempletID {
            get {
                return this.templetIDField;
            }
            set {
                this.templetIDField = value;
                this.RaisePropertyChanged("TempletID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string PrintAuditorGrade {
            get {
                return this.printAuditorGradeField;
            }
            set {
                this.printAuditorGradeField = value;
                this.RaisePropertyChanged("PrintAuditorGrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string PrintAuditorID {
            get {
                return this.printAuditorIDField;
            }
            set {
                this.printAuditorIDField = value;
                this.RaisePropertyChanged("PrintAuditorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string PrintAuditorName {
            get {
                return this.printAuditorNameField;
            }
            set {
                this.printAuditorNameField = value;
                this.RaisePropertyChanged("PrintAuditorName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FullTextSearchCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateConditionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumberConditionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedDocInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class DbTypeBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime defaultTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DefaultTime {
            get {
                return this.defaultTimeField;
            }
            set {
                this.defaultTimeField = value;
                this.RaisePropertyChanged("DefaultTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class ComplexCondition : DbTypeBase {
        
        private string paragraphNameField;
        
        private string complexElementIDField;
        
        private string complexElementNameField;
        
        private string selectedItemField;
        
        private string elementTextField;
        
        private int currentIdxField;
        
        private string comConDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ParagraphName {
            get {
                return this.paragraphNameField;
            }
            set {
                this.paragraphNameField = value;
                this.RaisePropertyChanged("ParagraphName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ComplexElementID {
            get {
                return this.complexElementIDField;
            }
            set {
                this.complexElementIDField = value;
                this.RaisePropertyChanged("ComplexElementID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ComplexElementName {
            get {
                return this.complexElementNameField;
            }
            set {
                this.complexElementNameField = value;
                this.RaisePropertyChanged("ComplexElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SelectedItem {
            get {
                return this.selectedItemField;
            }
            set {
                this.selectedItemField = value;
                this.RaisePropertyChanged("SelectedItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ElementText {
            get {
                return this.elementTextField;
            }
            set {
                this.elementTextField = value;
                this.RaisePropertyChanged("ElementText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CurrentIdx {
            get {
                return this.currentIdxField;
            }
            set {
                this.currentIdxField = value;
                this.RaisePropertyChanged("CurrentIdx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ComConDesc {
            get {
                return this.comConDescField;
            }
            set {
                this.comConDescField = value;
                this.RaisePropertyChanged("ComConDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class FullTextSearchCondition : DbTypeBase {
        
        private SearchType docSearchTypeField;
        
        private string paragraphNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SearchType DocSearchType {
            get {
                return this.docSearchTypeField;
            }
            set {
                this.docSearchTypeField = value;
                this.RaisePropertyChanged("DocSearchType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ParagraphName {
            get {
                return this.paragraphNameField;
            }
            set {
                this.paragraphNameField = value;
                this.RaisePropertyChanged("ParagraphName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public enum SearchType {
        
        /// <remarks/>
        AndSearch,
        
        /// <remarks/>
        OrSearch,
        
        /// <remarks/>
        BOOLSearch,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class BasicCondition : DbTypeBase {
        
        private string elementIDField;
        
        private string elementNameField;
        
        private string aliasField;
        
        private DataType dataTypeField;
        
        private string paragraphNameField;
        
        private string elementValueField;
        
        private DateConditionInfo dateConInfoField;
        
        private NumberConditionInfo numberConInfoField;
        
        private ElementType elementTypeField;
        
        private string conditionDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ElementID {
            get {
                return this.elementIDField;
            }
            set {
                this.elementIDField = value;
                this.RaisePropertyChanged("ElementID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ElementName {
            get {
                return this.elementNameField;
            }
            set {
                this.elementNameField = value;
                this.RaisePropertyChanged("ElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ParagraphName {
            get {
                return this.paragraphNameField;
            }
            set {
                this.paragraphNameField = value;
                this.RaisePropertyChanged("ParagraphName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ElementValue {
            get {
                return this.elementValueField;
            }
            set {
                this.elementValueField = value;
                this.RaisePropertyChanged("ElementValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DateConditionInfo DateConInfo {
            get {
                return this.dateConInfoField;
            }
            set {
                this.dateConInfoField = value;
                this.RaisePropertyChanged("DateConInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public NumberConditionInfo NumberConInfo {
            get {
                return this.numberConInfoField;
            }
            set {
                this.numberConInfoField = value;
                this.RaisePropertyChanged("NumberConInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ElementType ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
                this.RaisePropertyChanged("ElementType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ConditionDesc {
            get {
                return this.conditionDescField;
            }
            set {
                this.conditionDescField = value;
                this.RaisePropertyChanged("ConditionDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public enum DataType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        DateTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class DateConditionInfo : DbTypeBase {
        
        private System.DateTime lowerDateField;
        
        private System.DateTime upperDateField;
        
        private OpreatorType lowerOpreatorField;
        
        private OpreatorType upperOpreatorField;
        
        private string conditionDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime LowerDate {
            get {
                return this.lowerDateField;
            }
            set {
                this.lowerDateField = value;
                this.RaisePropertyChanged("LowerDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime UpperDate {
            get {
                return this.upperDateField;
            }
            set {
                this.upperDateField = value;
                this.RaisePropertyChanged("UpperDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OpreatorType LowerOpreator {
            get {
                return this.lowerOpreatorField;
            }
            set {
                this.lowerOpreatorField = value;
                this.RaisePropertyChanged("LowerOpreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public OpreatorType UpperOpreator {
            get {
                return this.upperOpreatorField;
            }
            set {
                this.upperOpreatorField = value;
                this.RaisePropertyChanged("UpperOpreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ConditionDesc {
            get {
                return this.conditionDescField;
            }
            set {
                this.conditionDescField = value;
                this.RaisePropertyChanged("ConditionDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public enum OpreatorType {
        
        /// <remarks/>
        Min,
        
        /// <remarks/>
        MinEqual,
        
        /// <remarks/>
        Max,
        
        /// <remarks/>
        MaxEqual,
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NoEqual,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public partial class NumberConditionInfo : DbTypeBase {
        
        private float lowerValueField;
        
        private float upperValueField;
        
        private OpreatorType lowerOpreatorField;
        
        private OpreatorType upperOpreatorField;
        
        private string conditionDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float LowerValue {
            get {
                return this.lowerValueField;
            }
            set {
                this.lowerValueField = value;
                this.RaisePropertyChanged("LowerValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float UpperValue {
            get {
                return this.upperValueField;
            }
            set {
                this.upperValueField = value;
                this.RaisePropertyChanged("UpperValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OpreatorType LowerOpreator {
            get {
                return this.lowerOpreatorField;
            }
            set {
                this.lowerOpreatorField = value;
                this.RaisePropertyChanged("LowerOpreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public OpreatorType UpperOpreator {
            get {
                return this.upperOpreatorField;
            }
            set {
                this.upperOpreatorField = value;
                this.RaisePropertyChanged("UpperOpreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ConditionDesc {
            get {
                return this.conditionDescField;
            }
            set {
                this.conditionDescField = value;
                this.RaisePropertyChanged("ConditionDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.healthcare.supcon.com/wsmeddoc/")]
    public enum ElementType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Outline,
        
        /// <remarks/>
        InputBox,
        
        /// <remarks/>
        SimpleOption,
        
        /// <remarks/>
        ComplexOption,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocServiceSoapChannel : PracticeForm.MedDocService.DocServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocServiceSoapClient : System.ServiceModel.ClientBase<PracticeForm.MedDocService.DocServiceSoap>, PracticeForm.MedDocService.DocServiceSoap {
        
        public DocServiceSoapClient() {
        }
        
        public DocServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short GetDocInfos(string szPatientID, string szVisitID, string szVisitType, System.DateTime dtVisitTime, string szDocTypeID, ref PracticeForm.MedDocService.MedDocInfo[] lstDocInfos) {
            return base.Channel.GetDocInfos(szPatientID, szVisitID, szVisitType, dtVisitTime, szDocTypeID, ref lstDocInfos);
        }
        
        public string ConvertToHTML(string szPatientID, string szVisitID, string[] arrDocIDs) {
            return base.Channel.ConvertToHTML(szPatientID, szVisitID, arrDocIDs);
        }
        
        public string GetDocsHTML(string[] arrDocIDs) {
            return base.Channel.GetDocsHTML(arrDocIDs);
        }
    }
}
